services:
  server:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      depends_on:
        db:
          condition: service_healthy
      restart: always
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "7543:5432"
    volumes:
       - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres-data: